services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stasera
      MYSQL_USER: stasera
      MYSQL_PASSWORD: stasera
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata: